theme: jekyll-theme-minimal
gems:
  - jekyll-sitemap

title: "Joshua Kerr"
description: "Ph.D. Candidate<br>in Philosophy<br>University of Oregon"

email: jkerr@uoregon.edu
website: joshuakerr.github.io
github: joshuakerr
linkedin: kerrjoshua
academiaedu: uoregon.academia.edu/JoshuaKerr
