remote_theme: academic
gem: "academic"

title: "Joshua D. Kerr"
description: "Ph.D. Candidate<br>in Philosophy<br>University of Oregon"

email: jkerr@uoregon.edu
website: joshuakerr.net
github: joshuakerr
linkedin: kerrjoshua
academiaedu: uoregon.academia.edu/JoshuaDKerr
