remote_theme: academic
gem: "academic"

title_html: "Joshua D. Kerr"
description: "Ph.D. Candidate<br>Department of Philosophy<br>University of Oregon"

email: jkerr@uoregon.edu
author_website: joshuakerr.net
