theme: jekyll-theme-minimal
gems:
  - jekyll-sitemap

title: "Joshua Kerr"
description: "Graduate Student in Philosophy, University of Oregon"

email: jkerr@uoregon.edu
website: http://joshuakerr.github.io/
github: joshuakerr
linkedin: kerrjoshua
academiaedu: uoregon.academia.edu/JoshuaKerr
