remote_theme: academic
gem: "academic"

title_html: "<b>Joshua</b>D.<b>Kerr</b>"
description: "Ph.D. Candidate<br>Department of Philosophy<br>University of Oregon"

email: jkerr@uoregon.edu
website: joshuakerr.net
github: joshuakerr
linkedin: kerrjoshua
academiaedu: uoregon.academia.edu/JoshuaDKerr
